# Generated by Django 5.1 on 2025-01-27 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiCharacters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=20)),
                ('bio', models.TextField(blank=True, null=True)),
                ('properties', models.JSONField(default=dict)),
                ('characterType', models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('EXCLUSIVE', 'EXCLUSIVE')], default=None, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('age', models.CharField(max_length=5, null=True)),
                ('gender', models.CharField(default=1, max_length=2)),
                ('is_verified', models.BooleanField(default=False, null=True)),
                ('is_blocked', models.BooleanField(default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FriendDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LLMServers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('server_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_type', models.CharField(choices=[('VOICE', 'VOICE'), ('IMAGE', 'IMAGE'), ('TEXT', 'TEXT')], default='VOICE', max_length=10)),
                ('content', models.TextField(default=None, null=True)),
                ('read_reciept', models.CharField(choices=[('read', 'read'), ('sent', 'sent')], default='sent', max_length=15)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='api.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefreshTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refresh_token', models.TextField(max_length=15, unique=True)),
                ('device_id', models.CharField(max_length=50, null=True)),
                ('expire_in', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('properties', models.JSONField(default=dict, null=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_initiator', to='api.customuser')),
                ('last_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.room'),
        ),
        migrations.CreateModel(
            name='UserAiCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(default='', max_length=20, null=True)),
                ('properties', models.JSONField(default=dict)),
                ('ai_character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_character', to='api.aicharacters')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ai', to='api.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='room',
            name='initiatee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_initiatee', to='api.useraicharacter'),
        ),
    ]
