# Generated by Django 5.1 on 2025-05-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraicharacter',
            name='ai_character',
        ),
        migrations.AlterField(
            model_name='aicharacters',
            name='characterType',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('EXCLUSIVE', 'EXCLUSIVE')], default='PUBLIC', max_length=20, null=True),
        ),
    ]
