# Generated by Django 5.1 on 2025-05-04 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_useraicharacter_ai_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraicharacter',
            name='ai_character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_character', to='api.aicharacters'),
        ),
    ]
