# Generated by Django 5.1 on 2025-05-04 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_useraicharacter_ai_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='last_message',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='room',
            name='last_message_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
